#!/usr/bin/env bash
# Generated by distill v0.4.0 — https://github.com/milvasic/distill

set -eu

# ══════════════════════════════════════════════════════════════════════════════
# CONFIG — edit this block or regenerate with:
#   distill --name "tinit" \
#     --asset-url "https://raw.githubusercontent.com/milvasic/tinit/refs/heads/main/tinit" \
#     --installer-url "https://raw.githubusercontent.com/milvasic/tinit/refs/heads/main/install.sh"
# ══════════════════════════════════════════════════════════════════════════════

BINARY_NAME="tinit"
INSTALL_DIR="/usr/local/bin"
ASSET_TYPE="script"
ASSET_URL="https://raw.githubusercontent.com/milvasic/tinit/refs/heads/main/tinit"
INSTALLER_URL="https://raw.githubusercontent.com/milvasic/tinit/refs/heads/main/install.sh"
# VERSION_URL=""  # only needed for ASSET_TYPE=binary

# ══════════════════════════════════════════════════════════════════════════════
# ENGINE — do not edit below this line
# ══════════════════════════════════════════════════════════════════════════════

INSTALL_PATH="${INSTALL_DIR}/${BINARY_NAME}"

# ── Help ──────────────────────────────────────────────────────────────────────
help() {
	colorize >&2 <<EOF
${BINARY_NAME} installer — install, update, or uninstall ${BINARY_NAME}.

Usage:
  install.sh [options]

Options:
  --uninstall           # Remove ${BINARY_NAME} from ${INSTALL_DIR}
  --yes, -y             # Auto-approve upgrade (useful for non-interactive / CI)
  help, --help, -h      # Show this message

Examples:
  # Install or update interactively
  bash -c "\$(curl -fsSL ${INSTALLER_URL})"

  # Install or update non-interactively
  bash -c "\$(curl -fsSL ${INSTALLER_URL})" -- --yes

  # Uninstall
  bash -c "\$(curl -fsSL ${INSTALLER_URL})" -- --uninstall

EOF
	exit 1
}

# ── Colors & logging ──────────────────────────────────────────────────────────
if [ -t 1 ]; then
	RED=$'\033[0;31m'
	GREEN=$'\033[0;32m'
	YELLOW=$'\033[0;33m'
	CYAN=$'\033[0;36m'
	BOLD=$'\033[1m'
	RESET=$'\033[0m'
else
	RED=""
	GREEN=""
	YELLOW=""
	CYAN=""
	BOLD=""
	RESET=""
fi

log() { printf "\n${BOLD}=== %s ===${RESET}\n" "$1" >&2; }
error() { printf "${RED}ERROR:${RESET} %s\n" "$1" >&2; }
ok() { printf "${GREEN}%s${RESET}\n" "$1"; }

# ── Help colorizer ───────────────────────────────────────────────────────────
colorize_line() {
	sed \
		-e "s/\\(^\\|[^[:alnum:]_'/-]\\)\\(install.sh\\)\\([^[:alnum:]_'/-]\\|$\\)/\\1${GREEN}\\2${RESET}\\3/g" \
		-e "s/\\(^\\|[^[:alnum:]_'-]\\)\\(help\\)\\([^[:alnum:]_'-]\\|$\\)/\\1${YELLOW}\\2${RESET}\\3/g" \
		-e "s/--[a-z][a-z-]*/${CYAN}&${RESET}/g" \
		-e "s/\([ ,]\)\(-[a-z]\)/\\1${CYAN}\\2${RESET}/g"
}

colorize() {
	local line pre post
	while IFS= read -r line; do
		if [[ "$line" == *'#'* ]]; then
			pre="${line%%#*}"
			post="${line#*#}"
			pre="$(printf '%s' "$pre" | colorize_line)"
			printf '%s%s#%s%s\n' "$pre" "$GREEN" "$post" "$RESET"
		else
			printf '%s\n' "$line" | colorize_line
		fi
	done
}

# ── Helpers ───────────────────────────────────────────────────────────────────

# Returns 0 if sudo is needed to write to INSTALL_DIR.
need_sudo() {
	! [ -w "$INSTALL_DIR" ]
}

# Run a command, prepending sudo only if required.
run_cmd() {
	if need_sudo; then
		sudo "$@"
	else
		"$@"
	fi
}

# Fetch a URL, writing content to stdout.
fetch_url() {
	if command -v curl >/dev/null 2>&1; then
		curl -fsSL "$1"
	elif command -v wget >/dev/null 2>&1; then
		wget -qO- "$1"
	else
		error "Neither curl nor wget found. Please install one and try again."
		exit 1
	fi
}

# Download the asset to a temp file; sets TMPFILE.
# Optional argument: version string — substituted for {VERSION} in ASSET_URL.
download_asset() {
	TMPFILE="$(mktemp)"
	local url
	url="$(echo "$ASSET_URL" | sed "s/{VERSION}/${1:-}/g")"
	if command -v curl >/dev/null 2>&1; then
		curl -fsSL "$url" -o "$TMPFILE"
	elif command -v wget >/dev/null 2>&1; then
		wget -qO "$TMPFILE" "$url"
	else
		error "Neither curl nor wget found. Please install one and try again."
		exit 1
	fi
}

# Extract VERSION="x.y.z" from a shell script file.
extract_version_script() {
	grep -m1 '^VERSION=' "$1" | sed 's/^VERSION="//;s/"$//'
}

# Get the remote (latest) version.
#   script: grepped from the downloaded asset (TMPFILE must already exist)
#   binary: fetched as plain text from VERSION_URL
get_remote_version() {
	case "$ASSET_TYPE" in
	script)
		extract_version_script "$TMPFILE"
		;;
	binary)
		if [ -z "${VERSION_URL:-}" ]; then
			error "VERSION_URL must be set when ASSET_TYPE=binary."
			exit 1
		fi
		fetch_url "$VERSION_URL"
		;;
	esac
}

# Get the version of the currently installed binary.
#   script: grepped from the installed file
#   binary: parsed from  binary --version  output (first x.y.z found)
get_installed_version() {
	case "$ASSET_TYPE" in
	script)
		extract_version_script "$INSTALL_PATH"
		;;
	binary)
		"$INSTALL_PATH" --version 2>&1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
		;;
	esac
}

# Compare two semver strings (X.Y.Z). Prints: greater | lesser | equal.
version_compare() {
	local v1="$1" v2="$2"

	if [ "$v1" = "$v2" ]; then
		echo "equal"
		return
	fi

	local i n1 n2
	for i in 1 2 3; do
		n1="$(echo "$v1" | cut -d. -f"$i")"
		n2="$(echo "$v2" | cut -d. -f"$i")"
		n1="${n1:-0}"
		n2="${n2:-0}"
		if [ "$n1" -gt "$n2" ]; then
			echo "greater"
			return
		elif [ "$n1" -lt "$n2" ]; then
			echo "lesser"
			return
		fi
	done

	echo "equal"
}

# ── Install / Update ──────────────────────────────────────────────────────────
install() {
	log "${BINARY_NAME} installer"

	# Sequencing differs by type: scripts are downloaded first (version is inside
	# the file); binaries need the version upfront to build the download URL.
	local remote_version
	case "$ASSET_TYPE" in
	script)
		download_asset
		trap 'rm -f "$TMPFILE"' EXIT
		remote_version="$(get_remote_version)"
		;;
	binary)
		remote_version="$(get_remote_version)"
		download_asset "$remote_version"
		trap 'rm -f "$TMPFILE"' EXIT
		;;
	esac

	if [ -z "$remote_version" ]; then
		error "Could not determine version from remote."
		exit 1
	fi

	# ── Fresh install ──────────────────────────────────────────────────────
	if [ ! -f "$INSTALL_PATH" ]; then
		run_cmd install -m 755 "$TMPFILE" "$INSTALL_PATH"
		ok "${BINARY_NAME} v${remote_version} installed to ${INSTALL_PATH}"
		return
	fi

	# ── Already installed — compare versions ───────────────────────────────
	local installed_version
	installed_version="$(get_installed_version)"

	if [ -z "$installed_version" ]; then
		error "Could not determine version of installed ${BINARY_NAME} at ${INSTALL_PATH}."
		exit 1
	fi

	local cmp
	cmp="$(version_compare "$remote_version" "$installed_version")"

	case "$cmp" in
	equal)
		ok "${BINARY_NAME} v${installed_version} is already installed and up to date."
		;;
	greater)
		if [ "$auto_yes" = true ]; then
			run_cmd install -m 755 "$TMPFILE" "$INSTALL_PATH"
			ok "${BINARY_NAME} updated from v${installed_version} to v${remote_version}."
		elif [ -t 0 ]; then
			printf "Update %s from ${BOLD}v%s${RESET} to ${BOLD}v%s${RESET}? [y/N] " \
				"$BINARY_NAME" "$installed_version" "$remote_version"
			read -r reply
			case "$reply" in
			[Yy] | [Yy][Ee][Ss])
				run_cmd install -m 755 "$TMPFILE" "$INSTALL_PATH"
				ok "${BINARY_NAME} updated from v${installed_version} to v${remote_version}."
				;;
			*)
				echo "Update cancelled."
				;;
			esac
		else
			error "A newer version (v${remote_version}) is available (installed: v${installed_version})."
			error "Run interactively or pass --yes to auto-approve the update."
			exit 1
		fi
		;;
	lesser)
		error "Installed version (v${installed_version}) is newer than remote (v${remote_version}). Aborting."
		exit 1
		;;
	esac
}

# ── Uninstall ─────────────────────────────────────────────────────────────────
uninstall() {
	log "${BINARY_NAME} uninstaller"

	if [ ! -f "$INSTALL_PATH" ]; then
		echo "${BINARY_NAME} is not installed at ${INSTALL_PATH}. Nothing to do."
		return
	fi

	run_cmd rm -f "$INSTALL_PATH"
	ok "${BINARY_NAME} removed from ${INSTALL_PATH}."

	local config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/${BINARY_NAME}"
	if [ -d "$config_dir" ]; then
		local remove_config=false

		if [ "$auto_yes" = true ]; then
			remove_config=true
		elif [ -t 0 ]; then
			printf "Remove configuration directory at ${BOLD}%s${RESET}? [y/N] " "$config_dir"
			read -r reply
			case "$reply" in
			[Yy] | [Yy][Ee][Ss])
				remove_config=true
				;;
			esac
		else
			error "Configuration directory exists at ${config_dir}"
			error "Run interactively or pass --yes to auto-remove it."
		fi

		if [ "$remove_config" = true ]; then
			rm -rf "$config_dir"
			ok "Configuration directory removed: ${config_dir}"
		fi
	fi
}

# ── Argument parsing & dispatch ───────────────────────────────────────────────
action="install"
auto_yes=false

for arg in "$@"; do
	case "$arg" in
	--uninstall) action="uninstall" ;;
	--yes | -y) auto_yes=true ;;
	help | --help | -h) help ;;
	*)
		error "Unknown option: $arg"
		help
		;;
	esac
done

case "$action" in
install) install ;;
uninstall) uninstall ;;
esac
