#!/usr/bin/env bash
# Regenerate install.sh with distill
# Generated by distill v0.3.2 - https://github.com/milvasic/distill

distill generate \
	--name "tinit" \
	--asset-url "https://raw.githubusercontent.com/milvasic/tinit/refs/heads/main/tinit" \
	--installer-url "https://raw.githubusercontent.com/milvasic/tinit/refs/heads/main/install.sh" \
	--install-dir "/usr/local/bin" \
	--asset-type "script"
